//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Client.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/", ConfigurationName="ServiceReferences.HelloWorldServiceSoap")]
    public interface HelloWorldServiceSoap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/HelloWorld", ReplyAction="*")]
        HelloWorld.Client.ServiceReferences.HelloWorldResponse HelloWorld(HelloWorld.Client.ServiceReferences.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWorld.Client.ServiceReferences.HelloWorldResponse> HelloWorldAsync(HelloWorld.Client.ServiceReferences.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/", Order=0)]
        public HelloWorld.Client.ServiceReferences.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelloWorld.Client.ServiceReferences.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/", Order=0)]
        public HelloWorld.Client.ServiceReferences.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelloWorld.Client.ServiceReferences.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.paradigmaxis.pt/isa/2015/06/08/hello-world/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldServiceSoapChannel : HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldServiceSoapClient : System.ServiceModel.ClientBase<HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap>, HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap {
        
        public HelloWorldServiceSoapClient() {
        }
        
        public HelloWorldServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWorld.Client.ServiceReferences.HelloWorldResponse HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap.HelloWorld(HelloWorld.Client.ServiceReferences.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string message) {
            HelloWorld.Client.ServiceReferences.HelloWorldRequest inValue = new HelloWorld.Client.ServiceReferences.HelloWorldRequest();
            inValue.Body = new HelloWorld.Client.ServiceReferences.HelloWorldRequestBody();
            inValue.Body.message = message;
            HelloWorld.Client.ServiceReferences.HelloWorldResponse retVal = ((HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWorld.Client.ServiceReferences.HelloWorldResponse> HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap.HelloWorldAsync(HelloWorld.Client.ServiceReferences.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWorld.Client.ServiceReferences.HelloWorldResponse> HelloWorldAsync(string message) {
            HelloWorld.Client.ServiceReferences.HelloWorldRequest inValue = new HelloWorld.Client.ServiceReferences.HelloWorldRequest();
            inValue.Body = new HelloWorld.Client.ServiceReferences.HelloWorldRequestBody();
            inValue.Body.message = message;
            return ((HelloWorld.Client.ServiceReferences.HelloWorldServiceSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
